export type PressKind = "review" | "interview" | "podcast" | "news";
export type PressStatus = "live" | "archive";

export type PressItem = {
  date: string;
  title: string;
  outlet: string;
  author?: string;
  kind: PressKind;
  status: PressStatus;
  href: string;
  note?: string;
};

export const pressItems: PressItem[] = [
  {
    date: "2014-06-14",
    title: "Movie Review: Blood Rush, Dead on Appraisal and Rabid Love",
    outlet: "WickedChannel",
    author: "JamesD",
    kind: "review",
    status: "live",
    href: "http://wickedchannel.com/2014/06/movie-review-blood-rush-dead-on-appraisal-and-rabid-love/",
    note: "Official Latest News page listed this as 8/10.",
  },
  {
    date: "2014-05-27",
    title: "Rabid Love team at the Alice D premiere in Los Angeles",
    outlet: "Official site recap",
    kind: "news",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://rabidlovemovie.com/latest-news.html",
  },
  {
    date: "2014-05-22",
    title: "Interview with Hannah Landberg",
    outlet: "Horror Society Radio",
    kind: "podcast",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://www.blogtalkradio.com/horrorsociety",
    note: "Original BlogTalkRadio episode page did not resolve in 2026 checks.",
  },
  {
    date: "2014-05-21",
    title: "Charm their Pants Off! A guide to being interviewed",
    outlet: "Ms. In the Biz",
    author: "Hayley Derryberry",
    kind: "interview",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://msinthebiz.com/2014/05/21/charm-pants-guide-interviewed/",
  },
  {
    date: "2014-05-16",
    title: "Rabid Love review",
    outlet: "The Horror Nation",
    author: "NecroBorg",
    kind: "review",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://www.thehorrornation.net/film-reviews1/rabid-love",
    note: "Official Latest News page listed this as 4/5. Domain no longer resolves.",
  },
  {
    date: "2014-05-10",
    title: "Interview with Brandon Stacy",
    outlet: "1313 Blood Lane",
    kind: "podcast",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://1313bloodlane.libsyn.com/episode-15",
  },
  {
    date: "2014-05-06",
    title: "Interview with the Rabid Love cast",
    outlet: "1313 Blood Lane",
    author: "Barry Morgan",
    kind: "podcast",
    status: "live",
    href: "http://directory.libsyn.com/episode/index/id/2822233",
  },
  {
    date: "2014-05-03",
    title: "An Interview with Hayley Derryberry",
    outlet: "UK Horror Scene",
    author: "Dean Sills",
    kind: "interview",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://www.ukhorrorscene.com/an-interview-with-hayley-derryberry-by-dean-sills/",
    note: "Live site timed out during 2026 verification.",
  },
  {
    date: "2014-04-14",
    title: "Solidarity",
    outlet: "Ms. In the Biz",
    author: "Alexandra Boylan",
    kind: "news",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://msinthebiz.com/2014/04/14/solidarity/",
  },
  {
    date: "2014-04-13",
    title: "100 Horror Movies Mission",
    outlet: "SFI Press / Chopping Block",
    author: "Brad",
    kind: "news",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://sfipress.com/100-horror-movies/",
  },
  {
    date: "2014-04-10",
    title: "Interview with Hayley Derryberry",
    outlet: "(re)Search my Trash",
    author: "Mike Haberfelner",
    kind: "interview",
    status: "live",
    href: "http://www.searchmytrash.com/articles/hayleyderryberry(4-14).shtml",
  },
  {
    date: "2014-04-04",
    title: "Zombie Media Database listing",
    outlet: "ZMDB",
    kind: "news",
    status: "live",
    href: "http://www.zmdb.org/movie/7704-Rabid_Love_(2013).htm",
  },
  {
    date: "2014-04-04",
    title: "Film Review: Rabid Love (2013)",
    outlet: "HorrorNews.net",
    author: "Jesse",
    kind: "review",
    status: "live",
    href: "https://horrornews.net/83678/film-review-rabid-love-2013/",
  },
  {
    date: "2014-04-01",
    title: "Interview with Paul J. Porter",
    outlet: "(re)Search my Trash",
    author: "Mike Haberfelner",
    kind: "interview",
    status: "live",
    href: "http://www.searchmytrash.com/articles/pauljporter(4-14).shtml",
  },
  {
    date: "2014-03-27",
    title: "Macabre Review: Rabid Love (2013)",
    outlet: "Necropolis Macabre",
    author: "Gravedigger Glen",
    kind: "review",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://necropolismacabre.com/2014/03/27/macabre-review-rabid-love-2013/",
  },
  {
    date: "2014-03-26",
    title: "Review – Rabid Love (2013)",
    outlet: "HorrorFix",
    author: "Ash",
    kind: "review",
    status: "live",
    href: "https://horror-fix.com/review-rabid-love/",
  },
  {
    date: "2014-03-26",
    title: "TCH Ep24: Paul J. Porter and Hayley Derryberry",
    outlet: "Horror Society Radio",
    kind: "podcast",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://www.blogtalkradio.com/horrorsociety/2014/03/26/tch-ep24-paul-j-porter-and-hayley-derryberry-of-rabid-love",
  },
  {
    date: "2014-03-20",
    title: "Rabid Love on Sci-Fi Sundae",
    outlet: "The Intellexual",
    kind: "podcast",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://theintellexual.com/rabid-love-on-sci-fi-sundae/",
  },
  {
    date: "2014-03-20",
    title: "Rabid Love (2013) review",
    outlet: "(re)Search my Trash",
    author: "Mike Haberfelner",
    kind: "review",
    status: "live",
    href: "http://www.searchmytrash.com/movies/rabidlove(2013).shtml",
  },
  {
    date: "2014-03-18",
    title: "NYFA Grads’ Feature Horror Rabid Love Available On Demand",
    outlet: "New York Film Academy",
    kind: "news",
    status: "live",
    href: "https://www.nyfa.edu/film-school-blog/nyfa-grads-feature-horror-rabid-love-available-on-demand/",
  },
  {
    date: "2014-03-16",
    title: "Interview: Hayley Derryberry & Paul J. Porter",
    outlet: "Legless Corpse",
    kind: "interview",
    status: "live",
    href: "http://leglesscorpse.us/interview-hayley-derryberry-paul-j-porter-rabid-love/",
  },
  {
    date: "2014-03-13",
    title: "Rabid Love (Review)",
    outlet: "Horror Society",
    author: "Blacktooth",
    kind: "review",
    status: "live",
    href: "https://www.horrorsociety.com/2014/03/13/rabid-love-review/",
  },
  {
    date: "2014-03-12",
    title: "Rabid Love",
    outlet: "Demons of Celluloid",
    kind: "review",
    status: "live",
    href: "http://demonsofcelluloid.blogspot.com/2014/03/rabid-love.html",
  },
  {
    date: "2014-03-11",
    title: "Rabid Love (2013)",
    outlet: "Legless Corpse",
    kind: "review",
    status: "live",
    href: "http://leglesscorpse.us/rabid-love-2013/",
  },
  {
    date: "2014-03-10",
    title: "Ain’t It Cool News coverage",
    outlet: "Ain't It Cool News",
    kind: "review",
    status: "live",
    href: "https://www.aintitcool.com/node/66438",
  },
  {
    date: "2014-03-07",
    title: "80s Grindhouse Throwback in Rabid Love",
    outlet: "Horror Movies Uncut",
    kind: "review",
    status: "live",
    href: "http://horrormoviesuncut.com/2014/03/07/80s-grindhouse-throwback-in-rabid-love/",
  },
  {
    date: "2014-03-04",
    title: "Interview with Hayley Derryberry",
    outlet: "Horribly Hooched",
    kind: "interview",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://horriblyhooched.com/2014/03/04/interview-with-hayley-derryberry-on-rabid-love/",
  },
  {
    date: "2014-03-03",
    title: "Rabid Love: 80s Horror with a Modern Day Twist",
    outlet: "ScareTissue",
    kind: "review",
    status: "live",
    href: "http://www.scaretissue.com/rabid-love-80s-horror-with-a-modern-day-twist/",
  },
  {
    date: "2014-03-03",
    title: "ST Interviews: Paul Porter and Hayley Derryberry",
    outlet: "ScareTissue",
    kind: "interview",
    status: "live",
    href: "http://www.scaretissue.com/st-interviews-rabid-loves-paul-porter-and-hayley-derryberry/",
  },
  {
    date: "2014-02-12",
    title: "Rabid Love review",
    outlet: "Horribly Hooched",
    kind: "review",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://horriblyhooched.com/2014/02/12/rabid-love/",
  },
  {
    date: "2014-01-27",
    title: "RABID LOVE Set for DVD / VOD Release on 3/4",
    outlet: "BroadwayWorld",
    kind: "news",
    status: "live",
    href: "https://www.broadwayworld.com/bwwmovies/article/RABID-LOVE-Set-for-DVD-VOD-Release-on-34-20140127",
  },
  {
    date: "2013-10-28",
    title: "Austin Film Fest 2013 Spotlight: Hayley Derryberry",
    outlet: "Gorno Blonde",
    kind: "interview",
    status: "live",
    href: "https://gornoblonde.wordpress.com/2013/10/28/austin-film-fest-2013-spotlight-sizzling-cutie-hayley-derryberry/",
  },
  {
    date: "2013-07-31",
    title: "Acquired by Acort International and Midnight Releasing",
    outlet: "BroadwayWorld",
    kind: "news",
    status: "live",
    href: "https://www.broadwayworld.com/bwwtv/article/RABID-LOVE-Acquired-by-Acort-International-and-Midnight-Releasing-20130731",
  },
  {
    date: "2013-07-30",
    title: "Deadly Beauty: Jessica Sonneborn",
    outlet: "Horror Society",
    kind: "interview",
    status: "live",
    href: "https://www.horrorsociety.com/2013/07/30/deadly-beauty-horrors-scream-queens-and-rising-talent-jessica-sonneborn/",
  },
  {
    date: "2013-07-30",
    title: "Indie Flick Rabid Love Scores Distro",
    outlet: "Dread Central",
    kind: "news",
    status: "live",
    href: "https://www.dreadcentral.com/news/69045/indie-flick-rabid-love-scores-distro",
  },
  {
    date: "2013-06-05",
    title: "Sink Your Teeth into The Trailer for Rabid Love",
    outlet: "Dread Central",
    author: "Steve Barton",
    kind: "news",
    status: "live",
    href: "https://www.dreadcentral.com/news/45014/sink-your-teeth-into-the-trailer-for-rabid-love/",
  },
  {
    date: "2013-06-04",
    title: "Geekscape 286: Rabid Love with Paul J. Porter and Hayley Derryberry",
    outlet: "Geekscape",
    kind: "podcast",
    status: "live",
    href: "https://www.geekscape.net/geekscape-286-rabid-love-with-paul-j-porter-and-hayley-derryberry",
  },
  {
    date: "2013-04-18",
    title: "13 Questions with Jessica Sonneborn",
    outlet: "Horror Society",
    kind: "interview",
    status: "live",
    href: "https://www.horrorsociety.com/2013/04/18/talking-with-the-dead-13-questions-with-jessica-sonneborn/",
  },
  {
    date: "2013-04-18",
    title: "First Trailer and L.A. Premiere",
    outlet: "Promote Horror",
    kind: "news",
    status: "live",
    href: "http://promotehorror.blogspot.com/2013/04/rabid-love-first-trailer-and-la-premiere.html",
  },
  {
    date: "2013-04-15",
    title: "13 Questions with Hayley Derryberry and Paul J. Porter",
    outlet: "Horror Society",
    kind: "interview",
    status: "live",
    href: "https://www.horrorsociety.com/2013/04/15/talking-with-the-dead-13-questions-with-hayley-derryberry-and-paul-j-porter/",
  },
  {
    date: "2013-04-15",
    title: "Rabid Love announcement",
    outlet: "Horror Society",
    kind: "news",
    status: "live",
    href: "https://www.horrorsociety.com/2013/04/15/rabid-love-2/",
  },
  {
    date: "2013-02-20",
    title: "80s Inspired Horror Film Rabid Love Trailer",
    outlet: "Igor's Lab",
    kind: "news",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://www.igorslab.com/home/2013/2/20/80s-inspired-horror-film-rabid-love-trailer.html",
  },
  {
    date: "2012-09-14",
    title: "Little Hollywood on the Prairie",
    outlet: "The Ruff Farm",
    kind: "interview",
    status: "live",
    href: "https://therufffarm.wordpress.com/2012/09/14/little-hollywood-on-the-prairie/",
    note: "Interview with production designer Lance L. Ziesch about filming in Hanston, Kansas.",
  },
  {
    date: "2012-03-20",
    title: "Classic Horror Gets Its Teeth Back",
    outlet: "Three If By Space",
    kind: "news",
    status: "archive",
    href: "https://web.archive.org/web/20160331185215/http://www.threeifbyspace.net/2012/03/rabid-love-classic-horror-gets-its-teeth-back/",
  },
  {
    date: "2012-03-19",
    title: "Rabid Love",
    outlet: "Promote Horror",
    kind: "news",
    status: "live",
    href: "http://promotehorror.blogspot.com/2012/03/rabid-love.html",
  },
  {
    date: "2012-02-23",
    title: "Rabid Love",
    outlet: "Horror Society",
    kind: "news",
    status: "live",
    href: "https://www.horrorsociety.com/2012/02/23/rabid-love/",
  },
];

export const pressKinds: { id: PressKind | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "review", label: "Reviews" },
  { id: "interview", label: "Interviews" },
  { id: "podcast", label: "Podcasts" },
  { id: "news", label: "News" },
];
